oarepo:doirequest
Narodni-repozitar/nr-datasets pull request #11
Opened 2021-11-01 13:15 UTC by Alzpeta

2021-11-01 13:26 UTC, Alzpeta commented
fixes https://github.com/Narodni-repozitar/nr-issues/issues/85

2021-11-04 16:27 UTC, mirekys requested changes

2021-11-04 16:27 UTC, mirekys commented on nr_datasets/jsonschemas/nr_datasets/nr-datasets-v1.0.0.json
> +        "oarepo:doirequest": {
Pole by melo byt soucasti knihovny `oarepo_doi_generator`, aby bylo reusable pro dalsi projekty. Preklep v nazvu, melo by byt `oarepo:doirequested`, jak se pouziva v mappingu a marshmallow

2021-11-05 09:19 UTC, mirekys commented on nr_datasets/jsonschemas/nr_datasets/nr-datasets-v1.0.0.json
> +        "oarepo:doirequest": {
UPDATE: sjednoceno na oarepo:doirequest, pouziva se na vic mistech

2021-11-05 11:16 UTC, mirekys approved these changes

2021-11-05 11:16 UTC, merged